# don't use product, use group instead
JOB_GROUP=gebit-build
JOB_PRODUCT=

JOB_UPSTREAM=[:]
JOB_MAIL_FAILURES=
JOB_XVFB=false
JOB_SITE_SEPARATE=false
JOB_MVN_OPTS=-Xmx512M -XX:MaxPermSize=256m 
JOB_INTEGRATION_TRIGGER=false
JOB_INTEGRATION_SITE=false
JOB_JDK=JDK11
JOB_DOCKER_LABELS=jenkins-slave-jdk11-maven
JOB_MAVEN=Maven 3.8
JOB_NIGHTLIES=false

# only build the branch configured with the seed job
JOB_SINGLE_BRANCH=true
