<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>plugin</artifactId>
    <version>2.29</version>
  </parent>

  <artifactId>maven-repo-cleaner</artifactId>
  <version>1.2-gebit12</version>
  <packaging>hpi</packaging>
  <name>Maven Repository Scheduled Cleanup Plugin</name>
  <url>https://wiki.jenkins-ci.org/display/JENKINS/Maven+Repo+Cleaner+Plugin</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    
    <!-- Version of the project (same as in version tag). It will be updated automatically by GEBIT flow. -->
    <version.maven-repo-cleaner>1.2-gebit12</version.maven-repo-cleaner>
    <version.property>version.maven-repo-cleaner</version.property>
    
    <project.build-name>maven-repo-cleaner</project.build-name>
		<project.jira>DINF</project.jira>
    
    <!-- Version of gebit-build to be used -->
    <version.build>3.4.1-I377</version.build>
    <version.gebit-build-extension>1.2.2</version.gebit-build-extension>
    <version.tiles>2.8-gebit37</version.tiles>
    <version.gitflow-maven-plugin>2.4.6-I152</version.gitflow-maven-plugin>
    
    <tiles.applyBefore>org.jenkins-ci.plugins:maven-repo-cleaner</tiles.applyBefore>
    <tiles.mergeTarget>${tiles.applyBefore}</tiles.mergeTarget>
    
    <flow.skipReleaseBranchMerge>true</flow.skipReleaseBranchMerge>
  </properties>



  <scm>
   <connection>scm:git:git://github.com/jenkinsci/maven-repo-cleaner-plugin.git</connection>
   <developerConnection>scm:git:git@github.com:jenkinsci/maven-repo-cleaner-plugin.git</developerConnection>
   <url>https://github.com/jenkinsci/maven-repo-cleaner-plugin</url>
    <tag>HEAD</tag>
  </scm>

  <developers>
    <developer>
      <id>abayer</id>
      <name>Andrew Bayer</name>
      <email>andrew.bayer@gmail.com</email>
      <timezone>-8</timezone>
    </developer>
    <developer>
      <id>olamy</id>
      <name>Olivier Lamy</name>
    </developer>
  </developers>

  <dependencies>
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>structs</artifactId>
      <version>1.14</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ant</groupId>
      <artifactId>ant</artifactId>
      <version>1.9.3</version>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.main</groupId>
      <artifactId>maven-plugin</artifactId>
      <version>3.0</version>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.6</version>
    </dependency>
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-repository-metadata</artifactId>
      <version>3.5.3</version>
    </dependency>
    <dependency>
      <groupId>org.apache.maven.indexer</groupId>
      <artifactId>indexer-artifact</artifactId>
      <version>5.1.2-4333789</version>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <version>2.3.2</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
    	<plugin>
        <groupId>io.repaint.maven</groupId>
        <artifactId>tiles-maven-plugin</artifactId>
        <version>${version.tiles}</version>
        <extensions>true</extensions>
        <configuration>
        	<applyBefore>${tiles.applyBefore}</applyBefore>
          <mergeTarget>${tiles.mergeTarget}</mergeTarget>
          	<tiles combine.children="append">
            	<tile>de.gebit.build.tile:build:${version.build}</tile>
              <!-- hier can be added other tiles to be used -->
            </tiles>
        </configuration>
   		</plugin>
    </plugins>
    <extensions>
	    <extension>
	      <groupId>de.gebit.build.maven</groupId>
	      <artifactId>gebit-build-extension</artifactId>
	      <version>${version.gebit-build-extension}</version>
	    </extension>
   	</extensions>
  </build>

  <distributionManagement>
    <!--  fix maven3 warning for id local -->
    <snapshotRepository>
      <!-- prevent accidental deployment of SNAPSHOTS to repository -->
      <id>local.repository</id>
      <url>file:.</url>
    </snapshotRepository>
  </distributionManagement>

  <!-- get every artifact through maven.glassfish.org, which proxies all the artifacts that we need -->
  <repositories>
    <repository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
      <releases>
         <enabled>false</enabled>
      </releases>
      <snapshots>
      	<enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>incrementals</id>
      <url>https://repo.jenkins-ci.org/incrementals/</url>
      <releases>
      	<enabled>false</enabled>
      </releases>
      <snapshots>
      	<enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
      <releases>
         <enabled>false</enabled>
      </releases>
      <snapshots>
      	<enabled>false</enabled>
      </snapshots>
    </pluginRepository>
    <pluginRepository>
      <id>incrementals</id>
      <url>https://repo.jenkins-ci.org/incrementals/</url>
      <releases>
      	<enabled>false</enabled>
      </releases>
      <snapshots>
      	<enabled>false</enabled>
      </snapshots>
		</pluginRepository>
  </pluginRepositories>

</project>
